/* generated by art/make_art.py: where each sprite frame sits on the 128x128 sprite page */
#ifndef ART_H
#define ART_H
/* frame = direction * 2 + walking frame; directions: RIGHT 0, LEFT 1, UP 2, DOWN 3 */
static const unsigned char doug_x[8] = { 0, 8, 16, 24, 32, 40, 48, 56 };
static const unsigned char doug_y[8] = { 0, 0, 0, 0, 0, 0, 0, 0 };
static const unsigned char vamp_x[4] = { 64, 72, 80, 88 };
static const unsigned char vamp_y[4] = { 0, 0, 0, 0 };
#define GOLD_GX 96
#define GOLD_GY 0
#define SPR_W 8   /* every sprite is 8x8 */
#endif
